'use strict'

module.exports = [
  {
    isAdmin: false,
    username: 'mtwycross0',
    password: 'xSNp1x03iL',
    firstName: 'Marianna',
    lastName: 'Twycross',
    email: 'mtwycross0@kickstarter.com',
    streetAddress: '03366 Spohn Junction',
    city: 'Lubbock',
    state: 'TX',
    zipCode: '79452',
  },
  {
    isAdmin: true,
    username: 'plinham1',
    password: 'hPhfqPv',
    firstName: 'Paxton',
    lastName: 'Linham',
    email: 'plinham1@gnu.org',
    streetAddress: '5 Summerview Drive',
    city: 'Louisville',
    state: 'KY',
    zipCode: '40280',
  },
  {
    isAdmin: false,
    username: 'mhasely2',
    password: 'j6h0k6txydB',
    firstName: 'Mic',
    lastName: 'Hasely',
    email: 'mhasely2@bbb.org',
    streetAddress: '864 Sutteridge Street',
    city: 'Waterbury',
    state: 'CT',
    zipCode: '06721',
  },
  {
    isAdmin: true,
    username: 'vwalter3',
    password: 'bPmoXQ9H',
    firstName: 'Valentine',
    lastName: 'Walter',
    email: 'vwalter3@issuu.com',
    streetAddress: '76922 Schiller Road',
    city: 'Atlanta',
    state: 'GA',
    zipCode: '30301',
  },
  {
    isAdmin: true,
    username: 'vcrunkhorn4',
    password: 'objY5LfoxDn',
    firstName: 'Vivie',
    lastName: 'Crunkhorn',
    email: 'vcrunkhorn4@nature.com',
    streetAddress: '5187 Michigan Place',
    city: 'Tulsa',
    state: 'OK',
    zipCode: '74108',
  },
  {
    isAdmin: false,
    username: 'cbalogun5',
    password: 'hILqdMKYkZ',
    firstName: 'Che',
    lastName: 'Balogun',
    email: 'cbalogun5@ft.com',
    streetAddress: '092 Kenwood Drive',
    city: 'Charlotte',
    state: 'NC',
    zipCode: '28247',
  },
  {
    isAdmin: true,
    username: 'twaryk6',
    password: '4sC9fyQIop7f',
    firstName: 'Tabby',
    lastName: 'Waryk',
    email: 'twaryk6@tamu.edu',
    streetAddress: '14 Oakridge Center',
    city: 'Lafayette',
    state: 'IN',
    zipCode: '47905',
  },
  {
    isAdmin: true,
    username: 'mmcbrearty7',
    password: 'TRpoG94',
    firstName: 'Mel',
    lastName: 'McBrearty',
    email: 'mmcbrearty7@miitbeian.gov.cn',
    streetAddress: '493 Helena Parkway',
    city: 'Indianapolis',
    state: 'IN',
    zipCode: '46254',
  },
  {
    isAdmin: false,
    username: 'dtotterdell8',
    password: 'leIWTFZ',
    firstName: 'Durward',
    lastName: 'Totterdell',
    email: 'dtotterdell8@barnesandnoble.com',
    streetAddress: '27 Old Gate Lane',
    city: 'Topeka',
    state: 'KS',
    zipCode: '66617',
  },
  {
    isAdmin: false,
    username: 'kminichi9',
    password: 'bQoQC76',
    firstName: 'Kahaleel',
    lastName: 'Minichi',
    email: 'kminichi9@mashable.com',
    streetAddress: '4902 Glacier Hill Drive',
    city: 'Little Rock',
    state: 'AR',
    zipCode: '72222',
  },
  {
    isAdmin: true,
    username: 'istratiffa',
    password: 'yc1mj55TXe',
    firstName: 'Ignace',
    lastName: 'Stratiff',
    email: 'istratiffa@cmu.edu',
    streetAddress: '88 Montana Road',
    city: 'Saint Cloud',
    state: 'MN',
    zipCode: '56372',
  },
  {
    isAdmin: false,
    username: 'ahickenb',
    password: 'HOMIDM058KJC',
    firstName: 'Amalita',
    lastName: 'Hicken',
    email: 'ahickenb@parallels.com',
    streetAddress: '642 Arkansas Junction',
    city: 'Virginia Beach',
    state: 'VA',
    zipCode: '23454',
  },
  {
    isAdmin: false,
    username: 'rgirhardc',
    password: 'zBtUrJmwc8i4',
    firstName: 'Riobard',
    lastName: 'Girhard',
    email: 'rgirhardc@dedecms.com',
    streetAddress: '54 Gulseth Point',
    city: 'Los Angeles',
    state: 'CA',
    zipCode: '90035',
  },
  {
    isAdmin: true,
    username: 'mdawdryd',
    password: 'KTjWMfHbH',
    firstName: 'Maxy',
    lastName: 'Dawdry',
    email: 'mdawdryd@earthlink.net',
    streetAddress: '604 Ludington Drive',
    city: 'Washington',
    state: 'DC',
    zipCode: '20010',
  },
  {
    isAdmin: true,
    username: 'fcopnalle',
    password: 'rWWCRLh',
    firstName: 'Friederike',
    lastName: 'Copnall',
    email: 'fcopnalle@ycombinator.com',
    streetAddress: '1469 Brickson Park Avenue',
    city: 'Pasadena',
    state: 'CA',
    zipCode: '91103',
  },
  {
    isAdmin: false,
    username: 'dfencottf',
    password: 'LTi79edP1',
    firstName: 'Dorelle',
    lastName: 'Fencott',
    email: 'dfencottf@discuz.net',
    streetAddress: '3268 Caliangt Plaza',
    city: 'Shreveport',
    state: 'LA',
    zipCode: '71161',
  },
  {
    isAdmin: false,
    username: 'hpleaving',
    password: 'afOLRG',
    firstName: 'Halette',
    lastName: 'Pleavin',
    email: 'hpleaving@miitbeian.gov.cn',
    streetAddress: '44 Waxwing Trail',
    city: 'New Haven',
    state: 'CT',
    zipCode: '06505',
  },
  {
    isAdmin: false,
    username: 'vprynh',
    password: '1SqNLwExr',
    firstName: 'Vallie',
    lastName: 'Pryn',
    email: 'vprynh@soundcloud.com',
    streetAddress: '3025 Garrison Terrace',
    city: 'Washington',
    state: 'DC',
    zipCode: '20238',
  },
  {
    isAdmin: true,
    username: 'cexoni',
    password: 'RPxyehk4T',
    firstName: 'Colette',
    lastName: 'Exon',
    email: 'cexoni@slashdot.org',
    streetAddress: '96203 Hudson Court',
    city: 'Greensboro',
    state: 'NC',
    zipCode: '27404',
  },
  {
    isAdmin: true,
    username: 'seberlej',
    password: 'jBSPlE26GQx',
    firstName: 'Sigmund',
    lastName: 'Eberle',
    email: 'seberlej@vk.com',
    streetAddress: '7844 Nova Alley',
    city: 'Littleton',
    state: 'CO',
    zipCode: '80161',
  },
  {
    isAdmin: true,
    username: 'ejedraszekk',
    password: '3u6b05',
    firstName: 'Etan',
    lastName: 'Jedraszek',
    email: 'ejedraszekk@toplist.cz',
    streetAddress: '12224 Badeau Place',
    city: 'Augusta',
    state: 'GA',
    zipCode: '30911',
  },
  {
    isAdmin: true,
    username: 'rhuntrissl',
    password: 'LOyOeQlHK',
    firstName: 'Raleigh',
    lastName: 'Huntriss',
    email: 'rhuntrissl@slate.com',
    streetAddress: '2 Surrey Alley',
    city: 'Durham',
    state: 'NC',
    zipCode: '27710',
  },
  {
    isAdmin: true,
    username: 'mcampesm',
    password: 'odV8hE',
    firstName: 'Merci',
    lastName: 'Campes',
    email: 'mcampesm@reddit.com',
    streetAddress: '312 Ludington Street',
    city: 'Portland',
    state: 'OR',
    zipCode: '97216',
  },
  {
    isAdmin: true,
    username: 'galbertn',
    password: 'SMnN5gjvU',
    firstName: 'Gaultiero',
    lastName: 'Albert',
    email: 'galbertn@amazon.com',
    streetAddress: '5094 Carpenter Terrace',
    city: 'Monticello',
    state: 'MN',
    zipCode: '55590',
  },
  {
    isAdmin: true,
    username: 'vboyetto',
    password: 'Y6UQ3j46',
    firstName: 'Vally',
    lastName: 'Boyett',
    email: 'vboyetto@rambler.ru',
    streetAddress: '4 Vermont Trail',
    city: 'Columbus',
    state: 'OH',
    zipCode: '43204',
  },
  {
    isAdmin: true,
    username: 'lhaslockep',
    password: 'azb64oktw59m',
    firstName: 'Louis',
    lastName: 'Haslock(e)',
    email: 'lhaslockep@rambler.ru',
    streetAddress: '301 Amoth Court',
    city: 'Colorado Springs',
    state: 'CO',
    zipCode: '80910',
  },
  {
    isAdmin: true,
    username: 'smenisq',
    password: '9PwhopxMYib',
    firstName: 'Shanna',
    lastName: 'Menis',
    email: 'smenisq@tuttocitta.it',
    streetAddress: '3521 Arrowood Center',
    city: 'Detroit',
    state: 'MI',
    zipCode: '48224',
  },
  {
    isAdmin: true,
    username: 'rbharr',
    password: '2Huu07YEGw',
    firstName: 'Rolf',
    lastName: 'Bhar',
    email: 'rbharr@scientificamerican.com',
    streetAddress: '5518 Cordelia Center',
    city: 'Waterbury',
    state: 'CT',
    zipCode: '06705',
  },
  {
    isAdmin: true,
    username: 'ymions',
    password: 'se1Wo9Ip',
    firstName: 'Yolanthe',
    lastName: 'Mion',
    email: 'ymions@salon.com',
    streetAddress: '405 Merrick Parkway',
    city: 'Minneapolis',
    state: 'MN',
    zipCode: '55412',
  },
  {
    isAdmin: false,
    username: 'oallertont',
    password: 'Mmo0sE',
    firstName: 'Olenka',
    lastName: 'Allerton',
    email: 'oallertont@soundcloud.com',
    streetAddress: '733 Carpenter Terrace',
    city: 'Pittsburgh',
    state: 'PA',
    zipCode: '15261',
  },
  {
    isAdmin: false,
    username: 'linceu',
    password: 'MHuI0jV5s83i',
    firstName: 'Lincoln',
    lastName: 'Ince',
    email: 'linceu@census.gov',
    streetAddress: '3 North Trail',
    city: 'New York City',
    state: 'NY',
    zipCode: '10090',
  },
  {
    isAdmin: false,
    username: 'lsimmellv',
    password: 'qyX7rNNYn',
    firstName: 'Lari',
    lastName: 'Simmell',
    email: 'lsimmellv@instagram.com',
    streetAddress: '2 Larry Terrace',
    city: 'Sioux Falls',
    state: 'SD',
    zipCode: '57193',
  },
  {
    isAdmin: false,
    username: 'bcleatorw',
    password: 'M6NKhEi9o3ii',
    firstName: 'Beatriz',
    lastName: 'Cleator',
    email: 'bcleatorw@bloglines.com',
    streetAddress: '94 Almo Alley',
    city: 'Washington',
    state: 'DC',
    zipCode: '20551',
  },
  {
    isAdmin: true,
    username: 'csollonx',
    password: '97PRTk00Pyx',
    firstName: 'Claudianus',
    lastName: 'Sollon',
    email: 'csollonx@newsvine.com',
    streetAddress: '4 Claremont Terrace',
    city: 'Dayton',
    state: 'OH',
    zipCode: '45490',
  },
  {
    isAdmin: false,
    username: 'jlealley',
    password: '9SL5grS3',
    firstName: 'Jami',
    lastName: 'Lealle',
    email: 'jlealley@flickr.com',
    streetAddress: '647 Springview Drive',
    city: 'Warren',
    state: 'OH',
    zipCode: '44485',
  },
  {
    isAdmin: true,
    username: 'jkinkadez',
    password: 'vdnGq0DVh2Ol',
    firstName: 'Jobie',
    lastName: 'Kinkade',
    email: 'jkinkadez@apple.com',
    streetAddress: '006 4th Hill',
    city: 'Indianapolis',
    state: 'IN',
    zipCode: '46239',
  },
  {
    isAdmin: true,
    username: 'rmontier10',
    password: '9QfT7cx',
    firstName: 'Ronica',
    lastName: 'Montier',
    email: 'rmontier10@flickr.com',
    streetAddress: '0150 Lien Parkway',
    city: 'Saint Paul',
    state: 'MN',
    zipCode: '55123',
  },
  {
    isAdmin: false,
    username: 'hhitzmann11',
    password: 'RL8SRNW7m',
    firstName: 'Hubey',
    lastName: 'Hitzmann',
    email: 'hhitzmann11@acquirethisname.com',
    streetAddress: '0 Valley Edge Street',
    city: 'Fresno',
    state: 'CA',
    zipCode: '93740',
  },
  {
    isAdmin: false,
    username: 'whindenberger12',
    password: 'KOF4QaYh',
    firstName: 'Weider',
    lastName: 'Hindenberger',
    email: 'whindenberger12@wunderground.com',
    streetAddress: '9797 Novick Park',
    city: 'Detroit',
    state: 'MI',
    zipCode: '48275',
  },
  {
    isAdmin: true,
    username: 'ddienes13',
    password: 'XkJo0H1qXCfa',
    firstName: 'Deck',
    lastName: 'Dienes',
    email: 'ddienes13@weebly.com',
    streetAddress: '78 Corben Point',
    city: 'Carson City',
    state: 'NV',
    zipCode: '89706',
  },
  {
    isAdmin: false,
    username: 'cstork14',
    password: 'SXFYyu',
    firstName: 'Carole',
    lastName: 'Stork',
    email: 'cstork14@simplemachines.org',
    streetAddress: '60 Riverside Crossing',
    city: 'Terre Haute',
    state: 'IN',
    zipCode: '47812',
  },
  {
    isAdmin: false,
    username: 'bduchart15',
    password: 'VmIIZv8o',
    firstName: 'Bernie',
    lastName: 'Duchart',
    email: 'bduchart15@youtube.com',
    streetAddress: '0 Tennessee Drive',
    city: 'Memphis',
    state: 'TN',
    zipCode: '38181',
  },
  {
    isAdmin: true,
    username: 'bdronsfield16',
    password: 'hmDfZS',
    firstName: 'Brennen',
    lastName: 'Dronsfield',
    email: 'bdronsfield16@prlog.org',
    streetAddress: '95553 Sachtjen Place',
    city: 'Iowa City',
    state: 'IA',
    zipCode: '52245',
  },
  {
    isAdmin: true,
    username: 'ferdes17',
    password: 'qwGa7fWz9nS',
    firstName: 'Franchot',
    lastName: 'Erdes',
    email: 'ferdes17@google.co.uk',
    streetAddress: '92868 Randy Hill',
    city: 'Birmingham',
    state: 'AL',
    zipCode: '35279',
  },
  {
    isAdmin: true,
    username: 'gquarlis18',
    password: 'Myk8atXL45',
    firstName: 'Georgine',
    lastName: 'Quarlis',
    email: 'gquarlis18@theguardian.com',
    streetAddress: '9339 Melrose Drive',
    city: 'New York City',
    state: 'NY',
    zipCode: '10150',
  },
  {
    isAdmin: false,
    username: 'byoudell19',
    password: 'vfebyQ5',
    firstName: 'Bertrando',
    lastName: 'Youdell',
    email: 'byoudell19@fc2.com',
    streetAddress: '36369 Artisan Parkway',
    city: 'Long Beach',
    state: 'CA',
    zipCode: '90831',
  },
  {
    isAdmin: false,
    username: 'lbrinsden1a',
    password: 'y4NNELUU',
    firstName: 'Lynnelle',
    lastName: 'Brinsden',
    email: 'lbrinsden1a@wix.com',
    streetAddress: '72 Russell Lane',
    city: 'Atlanta',
    state: 'GA',
    zipCode: '30328',
  },
  {
    isAdmin: true,
    username: 'gruffle1b',
    password: '9xNk2IT0i',
    firstName: 'Gavrielle',
    lastName: 'Ruffle',
    email: 'gruffle1b@hud.gov',
    streetAddress: '1 Waxwing Pass',
    city: 'Portland',
    state: 'OR',
    zipCode: '97221',
  },
  {
    isAdmin: false,
    username: 'glutzmann1c',
    password: '9TbCSHnodZ',
    firstName: 'Ginelle',
    lastName: 'Lutzmann',
    email: 'glutzmann1c@thetimes.co.uk',
    streetAddress: '1379 Village Green Pass',
    city: 'Pueblo',
    state: 'CO',
    zipCode: '81015',
  },
  {
    isAdmin: true,
    username: 'dvallentine1d',
    password: 'sUhpED',
    firstName: 'Dom',
    lastName: 'Vallentine',
    email: 'dvallentine1d@miibeian.gov.cn',
    streetAddress: '43 Corscot Court',
    city: 'Daytona Beach',
    state: 'FL',
    zipCode: '32128',
  },
  {
    isAdmin: true,
    username: 'iqualtro1e',
    password: '2HYkOUF',
    firstName: 'Iago',
    lastName: 'Qualtro',
    email: 'iqualtro1e@bing.com',
    streetAddress: '544 Hooker Plaza',
    city: 'Macon',
    state: 'GA',
    zipCode: '31217',
  },
  {
    isAdmin: true,
    username: 'hdowsey1f',
    password: 'FJzf8KxoKnRO',
    firstName: 'Howey',
    lastName: 'Dowsey',
    email: 'hdowsey1f@uol.com.br',
    streetAddress: '3 Summit Circle',
    city: 'Chicago',
    state: 'IL',
    zipCode: '60663',
  },
  {
    isAdmin: true,
    username: 'rpoat1g',
    password: 'sNFD7oJ5',
    firstName: 'Rodge',
    lastName: 'Poat',
    email: 'rpoat1g@hugedomains.com',
    streetAddress: '27457 Beilfuss Court',
    city: 'Arlington',
    state: 'TX',
    zipCode: '76004',
  },
  {
    isAdmin: true,
    username: 'qwhitsey1h',
    password: 'U7Gvixw',
    firstName: 'Quint',
    lastName: 'Whitsey',
    email: 'qwhitsey1h@ebay.com',
    streetAddress: '05 Hooker Crossing',
    city: 'Charleston',
    state: 'WV',
    zipCode: '25321',
  },
  {
    isAdmin: false,
    username: 'krolles1i',
    password: 'tQjVFXYYQ9S',
    firstName: 'Koralle',
    lastName: 'Rolles',
    email: 'krolles1i@deviantart.com',
    streetAddress: '299 Mallard Point',
    city: 'El Paso',
    state: 'TX',
    zipCode: '79928',
  },
  {
    isAdmin: true,
    username: 'ulufkin1j',
    password: 'C6x4THbxDCgy',
    firstName: 'Urbano',
    lastName: 'Lufkin',
    email: 'ulufkin1j@google.pl',
    streetAddress: '84 Melvin Terrace',
    city: 'Daytona Beach',
    state: 'FL',
    zipCode: '32123',
  },
]
